version: "3.9"

services:
  migrate:
    image: "migrate/migrate"
    networks:
      - CRMNet
    volumes:
      - ./migrations:/migrations
    command: >
      sh -c "until pg_isready -h postgres -p 5432; do sleep 5; done; 
             migrate -path /migrations -database postgres://postgres:123321@postgres:5432/crm_admin?sslmode=disable up"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres_product
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=crm_admin
    networks:
      - CRMNet
    ports:
      - 5436:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 3

  product:
    container_name: product
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - CRMNet
    ports:
      - "8070:8070"

networks:
  CRMNet:
    name: CRMNet
    driver: bridge

volumes:
  postgres_data:
  migrations: